import './broadcast-preview.css';
import {exampleProgramme} from './broadcast/fixtures.js';
import {compileTimeline,sceneState} from './broadcast/timeline.js';
import {renderSVG,escapeXML as esc} from './broadcast/render.js';
let p=exampleProgramme(),timeline=compileTimeline(p,{}, {fixture:true}),at=0,playing=false,last=0;
const checks=['identities','lipSync','dialogue','listeners','standingComposition','chartReadability','claimsAndSources','audio','disclosure','overallQuality'];
const labels={'anchor-full':'Anchor studio','discussion-two':'Two presenters','presenter-board':'Market board','anchor-analyst-wall':'Analyst at the wall','chart-full':'Chart analysis','story-visual':'Story & context'};
document.querySelector('#studio').innerHTML=`<header><strong>SIGNAL</strong><span>BROADCAST STUDIO / V2</span><a href="/">Back to channel ↗</a></header><main><div class="eyebrow">The bigger picture</div><h1>A newsroom, directed by the story.</h1><p>Explore six coordinated layouts, dialogue cues and data-driven graphics. This silent rehearsal uses illustrative figures and presenter placeholders.</p><div class="toolbar"><span class="tag">DESIGN REHEARSAL</span><label>Programme <select id="profile"><option value="sample">45-second scene sampler</option><option value="pilot">Five-minute rehearsal</option></select></label><label><input id="motion" type="checkbox"> Reduce motion</label></div><div id="screen" role="img" aria-label="Broadcast layout rehearsal"></div><div class="toolbar"><button id="play" class="primary">Play preview</button><input id="seek" aria-label="Programme position" type="range" min="0" max="44999" step="33"><output id="time"></output></div><nav class="scenes" aria-label="Scene layouts"></nav><div class="detail"><section class="card"><div class="eyebrow" id="speaker"></div><h2 id="scene-title"></h2><p id="utterance"></p><span class="tag">SCRIPT PREVIEW · NO GENERATED VOICE</span></section><section class="card"><h2>Evidence & direction</h2><dl id="source"></dl><ul class="events"></ul></section></div><details><summary>Private production review</summary><div id="review"><p>Available on the private local worker. Sign in with its review token to inspect rendered media and record feedback.</p><form id="login"><input type="password" id="token" autocomplete="off" placeholder="Review token" aria-label="Review token"><button>Sign in</button></form><div class="toolbar"><select id="runs" aria-label="Production run"><option value="">Choose a V2 run</option></select><button id="refresh">Refresh runs</button><button id="logout">Sign out</button></div><div id="run-detail"></div><p id="status" role="status"></p></div></details></main>`;
const $=s=>document.querySelector(s),fmt=ms=>new Date(ms).toISOString().slice(14,19);
$('#motion').checked=matchMedia('(prefers-reduced-motion: reduce)').matches;
function buildScenes(){const seen=new Set();$('.scenes').innerHTML=p.scenes.filter(s=>!seen.has(s.template)&&seen.add(s.template)).map(s=>`<button data-at="${s.startMs}"><small>${fmt(s.startMs)} / SCENE</small><b>${labels[s.template]}</b></button>`).join('');$('.scenes').querySelectorAll('button').forEach(b=>b.onclick=()=>{at=Number(b.dataset.at)+500;draw();});}
function draw(){const state=sceneState(p,at,timeline,{reducedMotion:$('#motion').checked});$('#screen').innerHTML=renderSVG(p,at,timeline,{fixture:true,reducedMotion:$('#motion').checked});$('#seek').value=at;$('#time').textContent=`${fmt(at)} / ${fmt(p.durationMs)}`;$('#scene-title').textContent=labels[state.scene.template];$('#speaker').textContent=state.turn?p.presenters.find(x=>x.id===state.turn.speakerId).name+' / scripted turn':'Handover';$('#utterance').textContent=state.turn?.text||'A short pause gives the next presenter room to respond.';const s=p.snapshots.find(x=>x.id===state.scene.snapshotId);$('#source').innerHTML=`<dt>${esc(s.instrument)} · ${esc(s.interval)}</dt><dd>${esc(s.source)} · ${esc(s.kind)}</dd><dt>Snapshot</dt><dd>${esc(s.asOf)} / ${esc(s.unit)}</dd><dt>Indicators</dt><dd>SMA 20 · EMA 20 · RSI 14 · MACD 12/26/9 · Volume</dd>`;$('.events').innerHTML=timeline.filter(c=>state.scene.turnIds.includes(c.turnId)).map(c=>`<li>${fmt(c.atMs)} · ${esc(c.action)} · ${c.atMs<=at?'executed':'scheduled'}</li>`).join('');$('.scenes').querySelectorAll('button').forEach(b=>b.classList.toggle('active',p.scenes.find(s=>s.startMs===Number(b.dataset.at))?.template===state.scene.template));}
$('#play').onclick=()=>{playing=!playing;if(at>=p.durationMs-50)at=0;$('#play').textContent=playing?'Pause':'Play preview';last=performance.now();};$('#seek').oninput=e=>{at=Number(e.target.value);draw();};$('#motion').onchange=draw;$('#profile').onchange=e=>{p=exampleProgramme(e.target.value);timeline=compileTimeline(p,{}, {fixture:true});at=0;$('#seek').max=p.durationMs-1;buildScenes();draw();};
function tick(now){if(playing&&now-last>=33){at=Math.min(p.durationMs-1,at+now-last);last=now;draw();if(at===p.durationMs-1){playing=false;$('#play').textContent='Play preview';}}requestAnimationFrame(tick);}buildScenes();draw();requestAnimationFrame(tick);
async function api(url,body){const r=await fetch(url,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json().catch(()=>({error:'Start the private worker to use production review'}));if(!r.ok)throw new Error(data.error||'Request failed');return data;}
const notice=e=>$('#status').textContent=e.message||String(e);
async function refresh(){const runs=await api('/api/pilot/v2/runs');$('#runs').innerHTML='<option value="">Choose a V2 run</option>'+runs.map(r=>`<option value="${esc(r.name)}">${esc(r.title)} · ${r.fixture?'rehearsal':'real'} · ${esc(r.state)}</option>`).join('');notice('Signed in.');}
$('#login').onsubmit=async e=>{e.preventDefault();try{await api('/api/pilot/login',{token:$('#token').value});$('#token').value='';await refresh();}catch(e){notice(e);}};$('#refresh').onclick=()=>refresh().catch(notice);$('#logout').onclick=async()=>{try{await api('/api/pilot/logout',{});$('#run-detail').innerHTML='';$('#runs').innerHTML='<option value="">Choose a V2 run</option>';notice('Signed out.');}catch(e){notice(e);}};
$('#runs').onchange=async()=>{const name=$('#runs').value;if(!name)return;try{const r=await api('/api/pilot/v2/runs/'+name);$('#run-detail').innerHTML=`<h2>${esc(r.episode.title)}</h2><p>${r.manifest.fixture?'Rehearsal — cannot receive film approval.':'Real media run — human quality review required.'} Technical QA: ${r.qa?.pass?'passed':'pending'}. ${r.qa?.synthetic?'Synthetic test media; approval blocked.':''}</p><video id="master" controls preload="metadata" src="/media/${esc(name)}/master.mp4"><track kind="captions" srclang="en" label="English" src="/media/${esc(name)}/captions.vtt" default></video><p id="review-cue"></p><form id="defect"><label>Turn <select id="defect-turn">${r.episode.turns.map(t=>`<option value="${esc(t.id)}">${esc(t.id)} · ${esc(t.speakerId)}</option>`).join('')}</select></label><select id="category" aria-label="Defect category">${['voice','lipSync','gesture','facts','graphics','timing','other'].map(x=>`<option>${x}</option>`).join('')}</select><textarea id="note" placeholder="Describe the issue at the current video time" required></textarea><button>Save timed feedback</button></form><details><summary>Approve this exact master</summary><form id="approval"><p>Confirm each item after watching the entire recording.</p><input id="reviewer" placeholder="Reviewer name" required>${checks.map(x=>`<label class="check"><input type="checkbox" name="${x}" required> ${x.replace(/[A-Z]/g,c=>' '+c.toLowerCase())}</label>`).join('')}<button ${r.manifest.fixture||!r.qa?.pass||r.qa?.synthetic?'disabled':''}>Record approval</button></form></details><h3>Source snapshots</h3>${r.episode.snapshots.map(s=>`<p>${esc(s.instrument)} · ${esc(s.source)} · ${esc(s.asOf)} · ${esc(s.kind)}</p>`).join('')}`;
  $('#master').ontimeupdate=()=>{const t=r.episode.turns.find(t=>$('#master').currentTime*1000>=t.startMs&&$('#master').currentTime*1000<t.startMs+t.durationMs);$('#review-cue').textContent=t?`${t.speakerId}: ${t.text}`:'Handover';if(t)$('#defect-turn').value=t.id;};
  $('#defect').onsubmit=async e=>{e.preventDefault();try{await api(`/api/pilot/v2/runs/${name}/defects`,{turnId:$('#defect-turn').value,atMs:Math.round($('#master').currentTime*1000),category:$('#category').value,note:$('#note').value});notice('Feedback saved for this programme revision.');}catch(e){notice(e);}};
  $('#approval').onsubmit=async e=>{e.preventDefault();try{await api(`/api/pilot/v2/runs/${name}/approve`,{reviewer:$('#reviewer').value,checks:Object.fromEntries(checks.map(x=>[x,$(`[name="${x}"]`).checked]))});notice('Approval saved for this exact master.');}catch(e){notice(e);}};
}catch(e){notice(e);}};
