export const demoScenes=[
  {label:'THE OPEN',headline:'THE BUSINESS OF A CHANGING WORLD',text:'Good evening, and welcome to Signal. I am your AI presenter. In this demonstration, we bring together a digital anchor, broadcast graphics, and a structured business bulletin. Our focus is clear reporting, a natural delivery, and a programme that feels at home on a financial news channel.'},
  {label:'THE EXPLAINER',headline:'WHAT MOVES A BUSINESS?',text:'Behind every business story are three questions. What is changing? Who is affected? And what should viewers watch next? Prices alone do not tell the whole story. Earnings, interest rates, and consumer demand provide context. Reliable reporting separates observed facts from interpretation.'},
  {label:'THE CLOSE',headline:'CLARITY. CONTEXT. SIGNAL.',text:'That is the role of Signal: to make complex developments easier to follow. This was an AI-generated presentation demonstration, without simulated breaking news or invented market prices. Thank you for watching.'}
];
export function createDemoRecorder(video){
  if(!window.MediaRecorder||!HTMLCanvasElement.prototype.captureStream)throw new Error('Recording is not supported in this browser.');
  if(video.readyState<2||!video.videoWidth)throw new Error('Connect the presenter and wait for video before recording.');
  const audio=video.srcObject?.getAudioTracks().filter(track=>track.readyState==='live')||[];
  if(!audio.length)throw new Error('No live presenter audio track is available. Recording was not started.');
  const canvas=document.createElement('canvas');canvas.width=1920;canvas.height=1080;const ctx=canvas.getContext('2d');
  let scene=demoScenes[0],frame,stopped=false;
  const draw=()=>{ctx.fillStyle='#08121f';ctx.fillRect(0,0,1920,1080);const scale=Math.min(1920/video.videoWidth,1080/video.videoHeight),w=video.videoWidth*scale,h=video.videoHeight*scale;ctx.drawImage(video,(1920-w)/2,(1080-h)/2,w,h);ctx.fillStyle='#091626ed';ctx.fillRect(0,845,1920,165);ctx.fillStyle='#d5fe4a';ctx.fillRect(0,845,1920,5);ctx.font='bold 38px sans-serif';ctx.fillText('SIGNAL',64,90);ctx.fillStyle='#fff';ctx.font='22px sans-serif';ctx.fillText('AI PRESENTATION DEMO',1510,88);ctx.fillStyle='#d5fe4a';ctx.font='bold 26px sans-serif';ctx.fillText(scene.label,64,898);ctx.fillStyle='#fff';ctx.font='bold 46px sans-serif';ctx.fillText(scene.headline,64,966);ctx.fillStyle='#07101b';ctx.fillRect(0,1010,1920,70);ctx.fillStyle='#c2cfde';ctx.font='22px sans-serif';ctx.fillText('SIGNAL FINANCIAL NETWORK    /    CONTROLLED DEMONSTRATION    /    AI-GENERATED PRESENTER',64,1054);frame=requestAnimationFrame(draw);};draw();
  const stream=canvas.captureStream(30);const audioClones=audio.map(track=>track.clone());audioClones.forEach(track=>stream.addTrack(track));
  const mime=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/mp4'].find(type=>MediaRecorder.isTypeSupported(type));
  if(!mime){cancelAnimationFrame(frame);stream.getTracks().forEach(t=>t.stop());throw new Error('No supported recording format found.');}
  const recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:8000000,audioBitsPerSecond:128000}),chunks=[];
  recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};
  const result=new Promise((resolve,reject)=>{recorder.onstop=()=>{cancelAnimationFrame(frame);stream.getTracks().forEach(t=>t.stop());resolve(new Blob(chunks,{type:mime}));};recorder.onerror=()=>{cancelAnimationFrame(frame);stream.getTracks().forEach(t=>t.stop());reject(new Error('Recording failed.'));};});result.catch(()=>{});recorder.start(1000);
  return {setScene(value){scene=value;},stop(){if(!stopped){stopped=true;recorder.stop();}return result;},extension:mime.includes('mp4')?'mp4':'webm'};
}
export function mountBroadcastDemo({getSession,isSpeaking,pause,setScene,restore}){
  const section=document.createElement('section');section.className='demo-console';section.innerHTML='<div><h2>Broadcast demonstration</h2><p>A controlled three-part bulletin, approximately one minute. Connect a presenter first. Recording combines the actual anchor video and audio with broadcast graphics.</p></div><div class="desk-prompts"><button class="primary" id="demo-run">Run broadcast demo</button><button class="secondary" id="demo-record">Record broadcast demo</button><button class="secondary" id="demo-stop">Stop demo</button><button class="secondary" id="demo-view">Broadcast view</button></div><p id="demo-status" role="status">Ready for a connected presenter. Sandbox sessions may end before the script finishes.</p><p id="demo-quality"></p><a id="demo-download" hidden>Download recording</a>';
  document.querySelector('.layout').before(section);
  let active=false,index=0,recording,timer,advance,started=false,downloadUrl;
  const status=section.querySelector('#demo-status'),video=document.querySelector('#avatar-video');
  function stop(message='Demo stopped. Start bulletin to resume the programme.'){
    if(!active)return;active=false;clearTimeout(timer);clearTimeout(advance);getSession()?.interrupt();restore();status.textContent=message;
    if(recording){const capture=recording;recording=null;capture.stop().then(blob=>{if(!blob.size){status.textContent+=' No recording data received.';return;}if(downloadUrl)URL.revokeObjectURL(downloadUrl);downloadUrl=URL.createObjectURL(blob);const link=section.querySelector('#demo-download');link.href=downloadUrl;link.download='signal-broadcast-demo.'+capture.extension;link.textContent='Download recording'+(index<demoScenes.length?' (may be partial)':'');link.hidden=false;}).catch(error=>status.textContent=error.message);}
  }
  function playScene(){if(!active)return;const session=getSession();if(!session){stop('Presenter disconnected. Recording may be partial.');return;}const scene=demoScenes[index];started=false;setScene(scene);recording?.setScene(scene);status.textContent=`Part ${index+1} of 3 · ${scene.label} · ${recording?'Recording':'Preview'}`;try{session.repeat(scene.text);}catch{stop('Presenter could not read the script.');return;}clearTimeout(timer);timer=setTimeout(()=>stop('Speech completion was not received. Demo stopped; any recording may be partial.'),45000);}
  async function run(record){if(active)return;if(isSpeaking()){status.textContent='Pause the current bulletin and wait for the presenter to stop, then run the demo.';return;}const session=getSession();if(!session||video.readyState<2){status.textContent='Connect the presenter in Presenter setup, wait for video, then run this demo.';return;}pause();try{if(record)recording=createDemoRecorder(video);}catch(error){status.textContent=error.message;return;}active=true;index=0;section.querySelector('#demo-download').hidden=true;playScene();}
  section.querySelector('#demo-run').onclick=()=>run(false);section.querySelector('#demo-record').onclick=()=>run(true);section.querySelector('#demo-stop').onclick=()=>stop();section.querySelector('#demo-view').onclick=()=>document.body.classList.toggle('broadcast-view');
  const qualityTimer=setInterval(()=>{const quality=video.getVideoPlaybackQuality?.();section.querySelector('#demo-quality').textContent=video.videoWidth?`Incoming video: ${video.videoWidth} × ${video.videoHeight}${quality?' · decoded frames '+quality.totalVideoFrames+' · dropped '+quality.droppedVideoFrames:''}. Recording canvas: 1920 × 1080; source detail is unchanged.`:'No decoded presenter video yet.';if(active&&!getSession())stop('Presenter disconnected; recording may be partial.');},1000);
  window.addEventListener('pagehide',()=>{stop();clearInterval(qualityTimer);if(downloadUrl)URL.revokeObjectURL(downloadUrl);});
  return {isActive:()=>active,speechStarted(){if(active)started=true;},speechEnded(){if(!active||!started)return;started=false;clearTimeout(timer);index++;if(index===demoScenes.length){stop('Demo completed. Review the recording for voice, lip-sync and picture quality.');return;}advance=setTimeout(playScene,1200);},stop};
}
