import './pilot.css';
import planned from '../pilot/episodes/pilot.json';

const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const time=n=>`${Math.floor(n/60).toString().padStart(2,'0')}:${Math.floor(n%60).toString().padStart(2,'0')}`;
let episode=planned,selected=0,current=null;
$('#studio').innerHTML=`<header><a class="brand" href="/">S I G N A L <span>PRODUCTION STUDIO</span></a><div class="header-right"><span class="dot"></span> APPROVAL PILOT <a href="/">Channel ↗</a></div></header>
<main><div class="heading"><div><p class="eyebrow">EPISODE 001 / FIVE-MINUTE BRIEF</p><h1>The bigger picture<span>.</span></h1><p class="intro">Two presenters. One clear story. A programme built for review.</p></div><div class="episode-tag"><strong>05:00</strong><span>1920 × 1080 / 30 FPS TARGET</span></div></div>
<div class="workspace"><section class="preview"><div class="section-label"><span>PROGRAMME MONITOR</span><span id="mode">PREPRODUCTION</span></div><div class="monitor"><video id="player" controls playsinline preload="metadata" hidden></video><div id="storyboard"><div class="screen-top"><b>S I G N A L</b><span>PREPARED PILOT</span></div><div class="screen-main"><small>THE BRIEF / 001</small><h2>The bigger<br>picture.</h2><p>Markets move. Context matters.</p><div class="orbit"><i></i><i></i><i></i><div>↗</div></div></div><div class="screen-foot"><span>MAYA / ANCHOR</span><span>DANIEL / MARKETS ANALYST</span></div><div class="screen-disclosure">STORYBOARD • MOVING PRESENTER FOOTAGE PENDING</div></div></div><div class="monitor-footer"><span id="play-status">A prepared programme · Illustrative data</span><a id="download" hidden>Download master ↓</a></div><div id="timeline" class="timeline" aria-label="Episode timeline"></div><div class="time-labels"><span>00:00</span><span>01:00</span><span>02:00</span><span>03:00</span><span>04:00</span><span>05:00</span></div><div class="shot-detail"><div><p class="eyebrow" id="shot-kicker"></p><h2 id="shot-title"></h2></div><span id="shot-time"></span><p id="dialogue"></p><div id="cards" class="cards"></div><details id="evidence"><summary>Source snapshot &amp; calculations</summary><div></div></details></div></section>
<aside><div class="section-label"><span>PRODUCTION DESK</span><span>01</span></div><div class="panel"><div class="panel-title"><h2>Ready for the next take</h2><span class="pill" id="job-status">DRAFT</span></div><p class="muted">The script and shot plan are ready to inspect. Real presenter footage and voices need a provider render or an imported take.</p><div class="stats"><div><strong>2</strong><span>Presenters</span></div><div><strong id="shots-count">15</strong><span>Directed shots</span></div><div><strong>7</strong><span>Sequences</span></div></div></div>
<div class="panel"><p class="eyebrow">LOCAL REVIEW WORKER</p><form id="login"><label for="token">Review token</label><div class="input-row"><input id="token" type="password" autocomplete="off" placeholder="Paste your local review token" required><button>Connect</button></div></form><div id="connected" hidden><label for="runs">Select a production run</label><select id="runs"></select><button id="refresh" class="secondary">Refresh run</button><button id="logout" class="text-button">Disconnect</button></div><p id="connection-status" role="status" class="muted">Run the worker locally to connect private footage.</p></div>
<div class="panel"><div class="panel-title"><h2>Quality gates</h2><span id="qa-badge" class="pill">PENDING</span></div><ul id="quality"><li><i></i>Actual moving presenters</li><li><i></i>Natural voices & lip sync</li><li><i></i>Timed graphics & accurate figures</li><li><i></i>Five-minute master & full review</li></ul><p id="qa-note" class="muted">A fixture render validates the workflow. It cannot pass final approval.</p><form id="approval" hidden><label for="reviewer">Reviewer name</label><input id="reviewer" required placeholder="Your name"><div id="checklist"></div><label for="notes">Review notes</label><textarea id="notes" rows="3"></textarea><button>Approve this exact master</button></form></div></aside></div>
<section class="rundown"><div class="section-label"><span>THE RUN OF SHOW</span><span>300 SECONDS / ENGLISH</span></div><div id="rundown"></div></section><footer>Original Signal production · AI presenters · Prepared audience question · Illustrative figures<span>THE BIGGER PICTURE. IN FOCUS.</span></footer></main>`;
function selectShot(index,seek=false){selected=index;const s=episode.shots[index];$('#shot-kicker').textContent=`${s.segment} / ${s.speaker?episode.presenters[s.speaker].name:'IDENT'}`;$('#shot-title').textContent=s.headline;$('#shot-time').textContent=`${time(s.start)} — ${time(s.start+s.duration)}`;$('#dialogue').textContent=s.text||'Opening ident. Music and studio reveal are added during finishing.';$('#cards').innerHTML=s.cards.map(c=>`<div><small>${esc(c.label)}</small><strong>${esc(c.value)}</strong></div>`).join('');$('#evidence div').innerHTML=s.sourceIds.map(sourceId=>{const source=episode.sources.find(item=>item.id===sourceId);return `<p><strong>${esc(source.kind.toUpperCase())}</strong> · ${esc(source.capturedAt)}<br>${esc(source.summary)}</p>`;}).join('');document.querySelectorAll('[data-shot]').forEach(el=>el.classList.toggle('active',Number(el.dataset.shot)===index));if(seek&&!$('#player').hidden)$('#player').currentTime=s.start;}
function draw(){
  $('#shots-count').textContent=episode.shots.length;
  $('#timeline').innerHTML=episode.shots.map((s,i)=>`<button style="flex:${s.duration}" data-shot="${i}" aria-label="Seek to ${esc(s.headline)} at ${time(s.start)}" title="${esc(s.headline)}"><span>${i+1}</span></button>`).join('');
  $('#rundown').innerHTML=episode.shots.map((s,i)=>`<button class="rundown-row" data-shot="${i}"><span class="shot-index">${String(i+1).padStart(2,'0')}</span><span class="shot-start">${time(s.start)}</span><span><small>${esc(s.segment)}</small><strong>${esc(s.headline)}</strong></span><span class="speaker">${s.speaker?esc(episode.presenters[s.speaker].name):'IDENT'}</span><span class="duration">${s.duration}s</span><span>↗</span></button>`).join('');
  document.querySelectorAll('[data-shot]').forEach(el=>el.addEventListener('click',()=>selectShot(Number(el.dataset.shot),true)));selectShot(0);
}
async function api(url,options={}){const r=await fetch(url,options);const data=await r.json().catch(()=>({error:'Open the local worker URL to review footage.'}));if(!r.ok)throw new Error(data.error||'Review worker unavailable');return data;}
const post=(url,data)=>api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
async function refreshRuns(){const runs=await api('/api/pilot/runs');$('#login').hidden=true;$('#connected').hidden=false;$('#runs').innerHTML=runs.map(r=>`<option value="${esc(r.name)}">${r.fixture?'Fixture':'Real'} · ${esc(r.state)} · ${esc(r.name.slice(-22))}</option>`).join('');$('#connection-status').textContent=runs.length?'Private worker connected.':'No runs yet. Initialize and render a pilot.';if(runs.length)await load();}
async function load(){const name=$('#runs').value;if(!name)return;current=await api(`/api/pilot/runs/${encodeURIComponent(name)}`);episode=current.episode;draw();const {qa,manifest,approval}=current;$('#mode').textContent=manifest.fixture?'FIXTURE REHEARSAL':'PREPARED PROGRAMME';$('#job-status').textContent=manifest.state.toUpperCase().replaceAll('-',' ');$('#player').hidden=!qa;$('#storyboard').hidden=!!qa;$('#download').hidden=!qa;
  $('#approval').hidden=true;
  if(qa){const media=`/media/${encodeURIComponent(name)}`;$('#player').src=`${media}/master.mp4`;$('#player').innerHTML=`<track kind="captions" src="${media}/captions.vtt" srclang="en" label="English${qa.fixture?' rehearsal':''}">`;$('#download').href=`${media}/master.mp4`;$('#download').download=`${name}.mp4`;
    $('#quality').innerHTML=Object.entries(qa.checks).map(([k,v])=>`<li class="${v?'passed':'waiting'}"><i></i>${esc(k.replace(/[A-Z]/g,c=>' '+c.toLowerCase()))}<span>${v?'PASS':'PENDING'}</span></li>`).join('');$('#qa-badge').textContent=approval?'APPROVED':qa.technicalPass?'REVIEW':'NOT FINAL';$('#qa-note').textContent=qa.fixture?'Silent fixture: composition and timing are testable. Human-quality voices and moving presenters are still pending.':approval?`Approved by ${approval.reviewer}. Approval is bound to this exact master.`:'Watch the full programme and complete every quality check.';
    $('#play-status').textContent=qa.fixture?'Silent fixture · Not an approval demo':`${qa.master.duration.toFixed(2)}s · Source footage recorded in QA report`;
    $('#approval').hidden=!qa.technicalPass||!!approval;$('#checklist').innerHTML=qa.review.items.map(t=>`<label class="check"><input type="checkbox" value="${esc(t)}" required>${esc(t)}</label>`).join('');
  }else{$('#player').removeAttribute('src');$('#qa-badge').textContent='PENDING';$('#qa-note').textContent='Render the programme to generate quality measurements.';$('#quality').innerHTML='<li><i></i>Awaiting a rendered master</li>';}
}
async function safe(fn){try{await fn();}catch(e){$('#connection-status').textContent=e.message;}}
$('#login').addEventListener('submit',e=>{e.preventDefault();safe(async()=>{await post('/api/pilot/login',{token:$('#token').value});$('#token').value='';await refreshRuns();});});
$('#refresh').addEventListener('click',()=>safe(load));$('#runs').addEventListener('change',()=>safe(load));$('#logout').addEventListener('click',()=>safe(async()=>{await post('/api/pilot/logout',{});location.reload();}));
$('#player').addEventListener('timeupdate',()=>{const n=episode.shots.findIndex(s=>$('#player').currentTime>=s.start&&$('#player').currentTime<s.start+s.duration);if(n>=0&&n!==selected)selectShot(n);});
$('#approval').addEventListener('submit',e=>{e.preventDefault();safe(async()=>{await post(`/api/pilot/runs/${encodeURIComponent($('#runs').value)}/approve`,{reviewer:$('#reviewer').value,notes:$('#notes').value,checks:[...document.querySelectorAll('#checklist input:checked')].map(el=>el.value),masterHash:current.qa.master.sha256});await load();});});
draw();
